### ISSUE TITLE
new mongodb-prebuilt failing with uncaughtExceptions (Maybe shrinkwrap?)

### ISSUE THREAD

**Issue by franky-continu** [mccormicka/Mockgoose#173] opened 2016-01-13 00:10 UTC
I created [Issue-11](https://github.com/winfinit/mongodb-prebuilt/issues/11) in mongodb-prebuilt because it is making my tests fail all of a sudden but I wonder if the issue should belong to Mockgoose.

Perhaps it can be solved by shrinkwrapping?

------------------------ update 5:20 pm MST

I added `"mongodb-prebuilt": "4.2.16",` to my devDependencies, as a result my `npm install` is outputing:

```sh
> mongodb-prebuilt@4.2.16 postinstall /Users/franky/Workspace/continu/continu-api/node_modules/mongodb-prebuilt
> node install.js

Completed: 26.0% (12.2mb / 47.1mb)
```

So far so good. I'll soon confirm by running `npm test`

------------------------ update 5:33 pm MST

#### Confirmed

mongodb-prebuilt version 4.2.16 works

**Comment by welps** [comment] 2016-01-13 01:09
I don't think this is a Mockgoose issue? Your workaround just constrains mongodb-prebuilt's version which is a direct dependency of your project. 

If it was Mockgoose's dependency of mongodb-prebuilt causing issues, the error path should be
    
    `/Users/franky/Workspace/continu/continu-api/node_modules/mockgoose/node_modules/mongodb-prebuilt/index.js:89:12` 

instead of:

    `/Users/franky/Workspace/continu/continu-api/node_modules/mongodb-prebuilt/index.js:89:12`

**Comment by franky-continu** [comment] 2016-01-13 01:14
[Mockgoose at npm](https://www.npmjs.com/package/mockgoose) under Dependencies

####Dependencies (2)
`mongodb-prebuilt, debug`

**Comment by franky-continu** [comment] 2016-01-13 01:17
I really wish it didn't depend on it. but it does. it makes my project need to download 47mb that I wish it didn't need to. :-)

`Done installing MongoDBmb / 47.1mb)`

**Comment by franky-continu** [comment] 2016-01-13 01:20
Also [Build](https://travis-ci.org/mccormicka/Mockgoose) is failing at Travis CI with the same error

**Comment by winfinit** [comment] 2016-01-13 02:30
@franky-continu i will fix this tomorrow morning, I already know what merge broke this... with 47MB issue, I could repackage mongodb, but I need to think on how to do it without continuously paying attention at mongodb releases, because mongod binary is 27mb, and regular zip compression brings it down to 8MB

**Comment by welps** [comment] 2016-01-13 04:12
To clarify, is 5.0.10 the last working version without this issue?

**Comment by franky-continu** [comment] 2016-01-13 10:56
@welps no, the issue is on the mongodb-prebuilt dependency, or because it's upgrade to version 4.4. Mockgoose dependency for mongodb-prebuilt is `"mongodb-prebuilt": "^4.4.2"` and I would guess that will always bring the mongodb-prebuilt with the issue.

Anyways Roman just mentioned he was going to fix the issue.

1) Thank you so much Roman, I'll be following this thread to get the latest. Mockgoose Rocks and we thank you for it.

2) Given the amazing stuff we do with Mockgoose for testing I really couldn't care less if it downloaded 100mb, but if it came down to 8 would be a nice bonus for sure.

**Comment by winfinit** [comment] 2016-01-13 15:40
this should be resolved in 5.2.1, please let me know if you are still experiencing any problems.

**Comment by awochna** [comment] 2016-01-13 16:01
Running my tests gives me the following: 

```
Message:
    Cannot read property 'emit' of undefined
Details:
    domain: [object Object]
    domainThrown: true
Stack:
TypeError: Cannot read property 'emit' of undefined
    at NativeConnection.<anonymous> (/vagrant/logger/node_modules/mockgoose/Mockgoose.js:35:23)
    at emitNone (events.js:67:13)
    at NativeConnection.emit (events.js:166:7)
    at NativeConnection.Object.defineProperty.set (/vagrant/logger/node_modules/mongoose/lib/connection.js:112:12)
    at /vagrant/logger/node_modules/mongoose/lib/connection.js:448:23
    at /vagrant/logger/node_modules/mongoose/lib/drivers/node-mongodb-native/connection.js:58:21
    at /vagrant/logger/node_modules/mongoose/node_modules/mongodb/lib/db.js:224:14
    at null.<anonymous> (/vagrant/logger/node_modules/mongoose/node_modules/mongodb/lib/server.js:234:9)
    at g (events.js:260:16)
    at emitTwo (events.js:87:13)
    at emit (events.js:172:7)
    at null.<anonymous> (/vagrant/logger/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:269:68)
    at g (events.js:260:16)
    at emitTwo (events.js:87:13)
    at emit (events.js:172:7)
    at null.<anonymous> (/vagrant/logger/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-core/lib/connection/pool.js:81:12)
    at g (events.js:260:16)
    at emitTwo (events.js:87:13)
    at emit (events.js:172:7)
    at Socket.<anonymous> (/vagrant/logger/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-core/lib/connection/connection.js:124:49)
    at Socket.g (events.js:260:16)
    at emitOne (events.js:77:13)
    ✓ should mock for mongoose
    1) "after each" hook for "should mock for mongoose"


  1 passing (2s)
  1 failing

  1)  "after each" hook for "should mock for mongoose":
     Error: timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.
```

My afterEach hook is resetting the database:

    afterEach(function (done) {
      mockgoose.reset(function () {
        done();
      });
    });

Removing the afterEach hook allows tests to continue running, but produces the same `Cannot read property 'emit' of undefined`

**Comment by winfinit** [comment] 2016-01-13 16:11
ok, lets try with 5.2.2, also if possible, can you please put a small test together for me, even if 5.2.2 resolved it, that way we can add it for future.

**Comment by awochna** [comment] 2016-01-13 17:20
It does fix it on my CI server, so there are probably some local changes that I made that introduce this issue. I'll put together some tests if I can find the cause, but I think we can close this issue.

**Closed** 2016-01-19 01:47 UTC
