### ISSUE TITLE
Error with ava: TypeError: callback is not a function

### ISSUE THREAD

**Issue by omnidan** [mccormicka/Mockgoose#204] opened 2016-04-12 18:22 UTC
I tried the example from README.md, but with ES6:

``` js
import mongoose from 'mongoose'
import mockgoose from 'mockgoose'

mockgoose(mongoose).then(function () {
  mongoose.connect('mongodb://example.com/TestingDB', function (err) {
    console.error(err)
  })
}) 
```

However, this fails with the following error:

```
  TypeError: callback is not a function
    start (/Users/dan/Development/projects/touchlay/platform/node_modules/mongodb-prebuilt/index.js:79:4)
    Object.start_server (/Users/dan/Development/projects/touchlay/platform/node_modules/mongodb-prebuilt/index.js:65:16)
    /Users/dan/Development/projects/touchlay/platform/node_modules/mockgoose/Mockgoose.js:144:42
    next (/Users/dan/Development/projects/touchlay/platform/node_modules/rimraf/rimraf.js:74:7)
    CB (/Users/dan/Development/projects/touchlay/platform/node_modules/rimraf/rimraf.js:110:9)
    FSReqWrap.oncomplete (/Users/dan/Development/projects/touchlay/platform/node_modules/rimraf/rimraf.js:225:7)
```

**Comment by winfinit** [comment] 2016-04-12 20:52
what version of node are you using and what OS?

**Comment by omnidan** [comment] 2016-04-12 21:56
@winfinit 

```
Node.js v5.7.0
darwin 15.3.0
```

**Comment by winfinit** [comment] 2016-04-13 21:12
help me out, when you say you are using it with es6, are you using babel, or you are passing some extra flags to node, or ...

because when i am running your example as is, I am getting:

```
(function (exports, require, module, __filename, __dirname) { import mongoose from 'mongoose';
                                                              ^^^^^^

SyntaxError: Unexpected token import
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
```

**Comment by omnidan** [comment] 2016-04-14 06:11
@winfinit I keep forgetting node.js doesn't implement `import` yet :sweat_smile: - I use babel, you can run it with `babel-node` (that's what I do for testing purposes)

**Comment by winfinit** [comment] 2016-04-14 20:57
@omnidan I am unable to duplicate this issue

here was my setup:
```
npm install --save-dev babel-cli
npm install babel-preset-es2015 --save-dev
echo '{ "presets": ["es2015"] }' > .babelrc
```

content of a bug/204.es6:
```javascript
"use strict"

import mongoose from 'mongoose'
import mockgoose from '../mockgoose'

mockgoose(mongoose).then(function () {
  mongoose.connect('mongodb://example.com/TestingDB', function (err) {
    console.log("err:", err);
    console.log("done");
    mongoose.disconnect();
  })
}) 
```

running bug/204.es6 script:
```
$ time node_modules/babel-cli/bin/babel-node.js bugs/204.es6
err: undefined
done

real	0m1.013s
user	0m0.924s
sys	0m0.118s
```

my system:
```
$ uname -a
Darwin foo-bar.local 15.4.0 Darwin Kernel Version 15.4.0: Fri Feb 26 22:08:05 PST 2016; root:xnu-3248.40.184~3/RELEASE_X86_64 x86_64
$ node_modules/babel-cli/bin/babel-node.js --version
6.7.5
$ node -v
v5.10.1
```

**Comment by omnidan** [comment] 2016-04-17 18:30
I've been sitting hours at this issue and I still have no idea why this is failing in my environment. Might have to do with [`ava`](https://github.com/sindresorhus/ava) or [`supertest`](https://github.com/visionmedia/supertest) but honestly I don't have a clue at all...

**Comment by omnidan** [comment] 2016-04-17 19:37
I finally managed to get it to work, this is how Mockgoose works fine with `ava`:

```
import test from 'ava'
import mongoose from 'mongoose'
import mockgoose from 'mockgoose'

test.before(t => mockgoose(mongoose))
test.afterEach(t => mockgoose.reset(err => {
  if (err) t.fail(err)
}))
```

**Comment by omnidan** [comment] 2016-04-17 20:19
Actually this seems to be an issue with the test runner `ava`, it runs tests in parallel which I think mockgoose doesn't like 😅

**Comment by winfinit** [comment] 2016-04-18 13:35
@omnidan thank you for this bug report and your for your time pinpointing this issue. I set myself up with some tests using ava, and will post updates in this issue.

**Comment by AbrahamAlcaina** [comment] 2016-04-18 13:41
I have the same issue.
```javascript
import test from 'ava';
import sut from './server';
import request from 'supertest-as-promised';
import mongoose from 'mongoose';
import mockgoose from 'mockgoose';

test.before(async t => {
    console.log('1');
    await mockgoose(mongoose);
    console.log('2');
    const Subscription = mongoose.model('Subscription');
    await Subscription.create({ id: 'found' })
});

test('send message to an existent subscription', async t => {
    const res = await request(sut).post('/api/found/message');
    t.is(res.status, 200);
});

test.after(t => mockgoose.reset(err => {
  if (err) t.fail(err)
}));
```

Only the 1 is printed

**Comment by jadamgreen1010** [comment] 2016-04-22 22:34
Are we sure about this?

I think the issue is here: https://github.com/mccormicka/Mockgoose/blob/master/Mockgoose.js#L144

mongodb-prebuilt takes a callback and doesn't check before trying to call it. If you don't pass a callback to mongod.start_server() then it errors like that.
https://github.com/winfinit/mongodb-prebuilt/blob/125940e0872c69d49d777218284bbedca273c66c/index.js#L35-L67

If you agree I can PR

**Comment by omnidan** [comment] 2016-04-22 23:06
@jadamgreen1010 Thanks for the hint! Manually adding a callback to `start_server` has fixed the issue for me. I hope a new version with this fix gets released soon :grin:

**Comment by jadamgreen1010** [comment] 2016-04-22 23:32
@omnidan You're welcome :)

I hope so too, although I think it's something that could (maybe should) be fixed on both sides - mongodb-prebuilt could look before it leaps with that callback so we wouldn't have to pass a dummy function just to keep it from erroring.

**Comment by omnidan** [comment] 2016-04-23 10:59
@jadamgreen1010 it probably makes sense to add the callback either way (at least to check for errors) :wink:

**Comment by jadamgreen1010** [comment] 2016-04-23 23:11
@omnidan I'd agree, but it seems (if my memory serves me right) that the cb is only being called when there's an error and not called with success. It looks like the 'startResult' code that start_server returns is the only way handle any case, so the cb would be redundant.

It seems to me...
Simple solution: dummy callback to start_server.
Best solution: Fix start_server in mongodb-prebuilt to always use the callback or returned code or at least allow both.

**Comment by jadamgreen1010** [comment] 2016-04-25 17:09
@winfinit @omnidan I added a hotfix dummy function w/ comments: https://github.com/mccormicka/Mockgoose/pull/208

**Comment by pataltechnologies** [comment] 2016-05-02 17:08
Any idea if this hotfix will be implemented? I've hit a bit of a roadblock with a project that it fixes for me.

**Comment by pibi** [comment] 2016-05-09 20:41
@jadamgreen1010 @SNeugber @winfinit , not sure why you are using a hacky dummy function when you can use the code that checks the return code right nto the callback. Since mongodb-prebuilt return error or exit codes !==0 as first argument on the callback, we can use it directly.

Please check #212

**Comment by pibi** [comment] 2016-05-10 07:48
Sorry guys, it seems to work only if winfinit/mongodb-prebuilt#25 is applied

**Comment by mindmelting** [comment] 2016-06-14 05:44
Just as an FYI, you can get around this issue temporarily by running ava in serial mode ```--serial```

**Comment by spearmootz** [comment] 2016-07-07 14:38
this is pretty old so just wanted to confirm this is an issue. im testing with mocha with no success.

**Comment by thomas-lee** [comment] 2016-07-07 15:52
I am new to mockgoose and using es2015. I don't know if it is a good place to ask question here.

I have already used babel-register and run with mocha.

If i am using es6 import, it will load the app before mocking the mongoose. So i can't mock the mongo. Any solutions? 

I can only mock like this in order to mock before connect the db and use memory rather mongo
```
import mongoose from 'mongoose';
import mockgoose from 'mockgoose';
import request from 'supertest';
import {expect} from 'chai';
// import app from '../../app';
mockgoose(mongoose);
var app = require('../../app');
```

Thanks

**Comment by omnidan** [comment] 2016-07-11 21:46
I am still having this issue, even with `ava --serial`:

```
  TypeError: callback is not a function
    start (/Users/dan/Development/projects/touchlay/platform/node_modules/mongodb-prebuilt/index.js:80:13)
    Object.start_server (/Users/dan/Development/projects/touchlay/platform/node_modules/mongodb-prebuilt/index.js:66:16)
    /Users/dan/Development/projects/touchlay/platform/node_modules/mockgoose/Mockgoose.js:144:42
```

**Comment by alexfoxy** [comment] 2016-07-18 09:59
I'm still getting this issue with my tape tests. I can run the tests one at a time but running more than one gives me: 

```
callback(child.status);
            ^

TypeError: callback is not a function
    at start (/Users/alexfox/amplify/noiz-notifier/node_modules/mongodb-prebuilt/index.js:80:13)
    at Object.start_server (/Users/alexfox/amplify/noiz-notifier/node_modules/mongodb-prebuilt/index.js:66:16)
    at /Users/alexfox/amplify/noiz-notifier/node_modules/mockgoose/Mockgoose.js:144:42
    at next (/Users/alexfox/amplify/noiz-notifier/node_modules/rimraf/rimraf.js:74:7)
    at FSReqWrap.CB [as oncomplete] (/Users/alexfox/amplify/noiz-notifier/node_modules/rimraf/rimraf.js:110:9)

```

Using mockgoose v6.0.3 & mongoose v4.5.4

**Comment by sonidodespacio** [comment] 2017-02-11 02:49
I moved back to mocha due this bug. I got here from MERN boiler plate. Got this same error when running `npm run test`.

**Comment by winfinit** [comment] 2017-03-01 03:12
Hello, I am not monitoring this project anymore, please resubmit it under mockgoose/mockgoose if this is still an issue with new 7.x release

**Closed by winfinit** 2017-03-01 03:12 UTC
